apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-aspnetcore-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      # kubernetes POD that will be targeted by the deployment
      app: hello-aspnetcore-pod
  template:
    metadata:
      labels:
        app: hello-aspnetcore-pod
    spec:
      containers:
        - name: hello-aspnet-container
          image: msittestacr.azurecr.io/helloaspnetcore:v1
          resources:
            limits:
              memory: "256Mi"
              cpu: "1000m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: hello-aspnetcore-service
spec:
  ports:
    - name: http-port 
      port: 9080
      targetPort: 80
  selector:
    app: hello-aspnetcore-pod
  type: LoadBalancer  
